version = 0.1

[default.deploy.parameters]
stack_name = "food-backend"
resolve_s3 = true
s3_prefix = "food-backend"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "AllowedOrigins=\"https://recipes.r-on-it.com,http://localhost:3010\""
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
